
---
- name: Remove virtual machine
  gather_facts: no
  vars_files:
    - var/vcenter_vars.yml
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "vm_rename"
        datacenter: "{{ datacenter_name }}"

    - name: Get VM "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        datacenter: "{{ datacenter_name }}"
        folder: /
        name: "{{ vm_name }}"
      register: vm_facts

    - name: Remove "{{ vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        cluster: "{{ cluster_name }}"
        name: "{{ vm_name }}"
        state: absent
        force: yes
      delegate_to: localhost
      register: facts



