
---
- name: Rename virtual machine from old name to new name using UUID
  gather_facts: no
  vars_files:
    - var/vcenter_vars.yml
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "testvm_4"
        new_vm_name: "vm_rename"
        datacenter: "{{ datacenter_name }}"
        cluster_name: "{{ cluster_name }}"

    - name: Get VM "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        datacenter: "{{ datacenter_name }}"
        folder: /
        name: "{{ vm_name }}"
      register: vm_facts

    - name: Rename "{{ vm_name }}" to "{{ new_vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        cluster: "{{ cluster_name }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ new_vm_name }}"



#virtual machine, vmware_guest module uses VMware UUID, which is unique across vCenter environment. This value is autogenerated and can not be changed. You will use vmware_guest_facts mod#ule to find virtual machine and get information about VMware UUID of the virtual machine.
